<script lang="ts">
  import { onMount } from "svelte";
  import { _ } from "svelte-i18n";
  import {
    fetchPollingTemplates,
    generateAutoPollings,
    savePolling,
    type PollingTemplateEnt,
    type NodeEnt,
    type PollingEnt,
  } from "../api";
  import { renderPollingType } from "../common";
  import {
    X,
    FileText,
    Search,
    Plus,
    Upload,
    CheckCircle2,
    Layers,
    ArrowUpDown,
    Check,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
  } from "@lucide/svelte";

  let {
    show = $bindable(false),
    nodeId = "",
    nodes = [],
    onSelect = () => {},
    onCreated = () => {},
  } = $props<{
    show: boolean;
    nodeId?: string;
    nodes?: NodeEnt[];
    onSelect?: (template: PollingTemplateEnt, prefilled?: Partial<PollingEnt>) => void;
    onCreated?: () => void;
  }>();

  let templates = $state<PollingTemplateEnt[]>([]);
  let searchQuery = $state("");
  let selectedType = $state("all");
  let selectedId = $state<number | null>(null);
  let isLoading = $state(false);
  let isAutoGenerating = $state(false);
  let autoGeneratedList = $state<PollingEnt[]>([]);
  let showAutoConfirm = $state(false);
  let sortField = $state<"ID" | "Name" | "Type" | "Mode">("ID");
  let sortAsc = $state(true);
  let targetNodeId = $state("");

  let pageSize = $state(10);
  let currentPage = $state(1);

  $effect(() => {
    if (show) {
      targetNodeId = nodeId || (nodes[0]?.id || nodes[0]?.ID || "");
      loadTemplates();
    } else {
      selectedId = null;
      searchQuery = "";
      showAutoConfirm = false;
      autoGeneratedList = [];
      currentPage = 1;
    }
  });

  $effect(() => {
    // Reset page whenever search or filter or sort changes
    searchQuery;
    selectedType;
    sortField;
    sortAsc;
    currentPage = 1;
  });

  const loadTemplates = async () => {
    isLoading = true;
    try {
      templates = await fetchPollingTemplates();
      if (templates.length > 0 && selectedId === null) {
        selectedId = templates[0].ID;
      }
    } catch (e) {
      console.error("Failed to load polling templates:", e);
    } finally {
      isLoading = false;
    }
  };

  const types = $derived.by(() => {
    const set = new Set<string>();
    templates.forEach((t) => {
      if (t.Type) set.add(t.Type);
    });
    return ["all", ...Array.from(set).sort()];
  });

  const filteredTemplates = $derived.by(() => {
    let list = templates.filter((t) => {
      if (selectedType !== "all" && t.Type !== selectedType) return false;
      if (!searchQuery.trim()) return true;
      const q = searchQuery.toLowerCase();
      return (
        t.Name.toLowerCase().includes(q) ||
        t.Type.toLowerCase().includes(q) ||
        t.Mode.toLowerCase().includes(q) ||
        t.Descr.toLowerCase().includes(q)
      );
    });

    list.sort((a, b) => {
      let va: any = a[sortField];
      let vb: any = b[sortField];
      if (typeof va === "string") {
        va = va.toLowerCase();
        vb = vb.toLowerCase();
      }
      if (va < vb) return sortAsc ? -1 : 1;
      if (va > vb) return sortAsc ? 1 : -1;
      return 0;
    });

    return list;
  });

  const totalCount = $derived(filteredTemplates.length);
  const totalPages = $derived(
    pageSize === -1 ? 1 : Math.max(1, Math.ceil(totalCount / pageSize))
  );
  const validCurrentPage = $derived(
    Math.min(Math.max(1, currentPage), totalPages)
  );

  const paginatedTemplates = $derived.by(() => {
    const list = filteredTemplates;
    if (pageSize === -1) return list;
    const start = (validCurrentPage - 1) * pageSize;
    return list.slice(start, start + pageSize);
  });

  const rangeFrom = $derived(
    totalCount === 0
      ? 0
      : pageSize === -1
      ? 1
      : (validCurrentPage - 1) * pageSize + 1
  );
  const rangeTo = $derived(
    pageSize === -1
      ? totalCount
      : Math.min(validCurrentPage * pageSize, totalCount)
  );

  const selectedTemplate = $derived(
    templates.find((t) => t.ID === selectedId) || null
  );

  const handleSort = (field: "ID" | "Name" | "Type" | "Mode") => {
    if (sortField === field) {
      sortAsc = !sortAsc;
    } else {
      sortField = field;
      sortAsc = true;
    }
  };

  const handleApply = async () => {
    if (!selectedTemplate) return;

    // Check if template has AutoParam (e.g., ifIndex) and a target node is selected
    if (selectedTemplate.AutoParam && targetNodeId) {
      isAutoGenerating = true;
      try {
        const autoList = await generateAutoPollings(targetNodeId, selectedTemplate.ID);
        if (autoList.length > 1) {
          autoGeneratedList = autoList;
          showAutoConfirm = true;
          isAutoGenerating = false;
          return;
        }
      } catch (err) {
        console.warn("Auto param interface generation fell back to single template:", err);
      } finally {
        isAutoGenerating = false;
      }
    }

    // Apply single template to PollingDialog
    const prefilled: Partial<PollingEnt> = {
      name: selectedTemplate.Name,
      type: selectedTemplate.Type || "ping",
      mode: selectedTemplate.Mode,
      params: selectedTemplate.Params,
      filter: selectedTemplate.Filter,
      extractor: selectedTemplate.Extractor,
      script: selectedTemplate.Script,
      level: selectedTemplate.Level || "off",
      node_id: targetNodeId,
    };
    onSelect(selectedTemplate, prefilled);
    show = false;
  };

  const handleCreateBlank = () => {
    onSelect({
      ID: 0,
      Name: "",
      Level: "off",
      Type: "ping",
      Mode: "",
      Params: "",
      Filter: "",
      Extractor: "",
      Script: "",
      Descr: "",
      AutoParam: "",
    }, {
      name: "",
      type: "ping",
      node_id: targetNodeId,
      level: "off",
    });
    show = false;
  };

  const handleSaveBulkAuto = async () => {
    isAutoGenerating = true;
    try {
      for (const p of autoGeneratedList) {
        await savePolling(p);
      }
      onCreated();
      show = false;
    } catch (err) {
      console.error("Bulk save error:", err);
    } finally {
      isAutoGenerating = false;
    }
  };

  const handleImportFile = (e: Event) => {
    const input = e.target as HTMLInputElement;
    if (!input.files || input.files.length === 0) return;
    const file = input.files[0];
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const content = event.target?.result as string;
        const pt = JSON.parse(content);
        if (pt && typeof pt === "object") {
          const prefilled: Partial<PollingEnt> = {
            name: pt.Name || pt.name || "Imported Polling",
            type: pt.Type || pt.type || "ping",
            mode: pt.Mode || pt.mode || "",
            params: pt.Params || pt.params || "",
            filter: pt.Filter || pt.filter || "",
            extractor: pt.Extractor || pt.extractor || "",
            script: pt.Script || pt.script || "",
            level: pt.Level || pt.level || "off",
            node_id: targetNodeId,
          };
          onSelect({
            ID: 0,
            Name: prefilled.name || "",
            Level: prefilled.level || "off",
            Type: prefilled.type || "ping",
            Mode: prefilled.mode || "",
            Params: prefilled.params || "",
            Filter: prefilled.filter || "",
            Extractor: prefilled.extractor || "",
            Script: prefilled.script || "",
            Descr: pt.Descr || pt.descr || "Imported from template",
            AutoParam: pt.AutoParam || "",
          }, prefilled);
          show = false;
        }
      } catch (err) {
        alert("Invalid JSON template file");
      }
    };
    reader.readAsText(file);
  };
</script>

{#if show}
  <div
    role="dialog"
    aria-modal="true"
    tabindex="-1"
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
    onkeydown={(e) => e.key === "Escape" && (show = false)}
  >
    <div
      class="w-full max-w-6xl rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-2xl overflow-hidden flex flex-col max-h-[92vh] text-slate-800 dark:text-slate-100 font-sans"
    >
      <!-- Header -->
      <div
        class="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 px-5 py-3.5 bg-slate-50 dark:bg-slate-950/80"
      >
        <div class="flex items-center gap-2.5">
          <div
            class="flex h-8 w-8 items-center justify-center rounded-xl bg-blue-500/10 border border-blue-500/30 text-blue-500 dark:text-blue-400"
          >
            <Layers class="h-4 w-4" />
          </div>
          <div>
            <h3 class="text-sm font-bold text-slate-900 dark:text-slate-100">
              {$_("AddPolling.SelectTemplateTitle")}
            </h3>
            <p class="text-[11px] text-slate-500 dark:text-slate-400">
              {$_("AddPolling.SelectTemplateSubtitle")}
            </p>
          </div>
        </div>
        <button
          type="button"
          onclick={() => (show = false)}
          class="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-700 dark:text-slate-200 transition-colors cursor-pointer"
          title={$_("common.close")}
        >
          <X class="h-4 w-4" />
        </button>
      </div>

      {#if showAutoConfirm}
        <!-- Auto Param Bulk Confirm View -->
        <div class="flex-1 overflow-y-auto p-5 space-y-4 text-xs">
          <div
            class="rounded-xl border border-blue-200 dark:border-blue-900/50 bg-blue-50/50 dark:bg-blue-950/30 p-4"
          >
            <h4 class="font-bold text-blue-900 dark:text-blue-200 text-sm mb-1">
              {$_("AddPolling.AutoGeneratedInterfaces", { values: { count: autoGeneratedList.length } })}
            </h4>
            <p class="text-slate-600 dark:text-slate-400 mb-3">
              {$_("AddPolling.AutoGeneratedDesc")}
            </p>
            <div class="max-h-60 overflow-y-auto rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
              <table class="w-full text-left text-xs">
                <thead class="bg-slate-50 dark:bg-slate-800/60 text-slate-500 border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th class="p-2">名前</th>
                    <th class="p-2">パラメータ (OID/Index)</th>
                    <th class="p-2">レベル</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                  {#each autoGeneratedList as p}
                    <tr class="hover:bg-slate-50/50 dark:hover:bg-slate-800/40">
                      <td class="p-2 font-medium">{p.Name || p.name}</td>
                      <td class="p-2 font-mono text-slate-500">{p.Params || p.params}</td>
                      <td class="p-2 uppercase text-[10px] font-bold">{p.Level || p.level}</td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          </div>
          <div class="flex justify-end gap-2 pt-2">
            <button
              type="button"
              onclick={() => (showAutoConfirm = false)}
              class="px-4 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-700 cursor-pointer"
            >
              {$_("AddPolling.Back")}
            </button>
            <button
              type="button"
              disabled={isAutoGenerating}
              onclick={handleSaveBulkAuto}
              class="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold flex items-center gap-1.5 shadow-sm cursor-pointer disabled:opacity-50"
            >
              <Check class="h-4 w-4" />
              {isAutoGenerating
                ? "登録中..."
                : $_("AddPolling.BulkRegister", { values: { count: autoGeneratedList.length } })}
            </button>
          </div>
        </div>
      {:else}
        <!-- Filter Toolbar -->
        <div
          class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 dark:border-slate-800 px-5 py-2.5 bg-slate-50/50 dark:bg-slate-900/50 text-xs"
        >
          <!-- Search input -->
          <div class="relative w-72">
            <Search
              class="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400"
            />
            <input
              type="text"
              bind:value={searchQuery}
              placeholder={$_("AddPolling.SearchPlaceholder")}
              class="w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 pl-8 pr-3 py-1.5 text-slate-900 dark:text-slate-100 focus:border-blue-500 focus:outline-none"
            />
          </div>

          <!-- Type filter & Node selector -->
          <div class="flex items-center gap-2">
            <label for="template-type-filter" class="text-slate-500 whitespace-nowrap">
              {$_("polling.type")}:
            </label>
            <select
              id="template-type-filter"
              bind:value={selectedType}
              class="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 px-2.5 py-1.5 text-slate-900 dark:text-slate-100 focus:border-blue-500 focus:outline-none cursor-pointer"
            >
              {#each types as t}
                <option value={t}>
                  {t === "all" ? "すべて (All)" : renderPollingType(t)}
                </option>
              {/each}
            </select>

            {#if nodes.length > 0}
              <label for="template-target-node" class="text-slate-500 whitespace-nowrap ml-2">
                {$_("polling.targetNode")}:
              </label>
              <select
                id="template-target-node"
                bind:value={targetNodeId}
                class="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 px-2.5 py-1.5 text-slate-900 dark:text-slate-100 focus:border-blue-500 focus:outline-none max-w-[220px] truncate cursor-pointer"
              >
                {#each nodes as n}
                  <option value={n.id || n.ID}>
                    {n.name || n.Name} ({n.ip || n.IP})
                  </option>
                {/each}
              </select>
            {/if}
          </div>
        </div>

        <!-- Table list -->
        <div class="flex-1 overflow-y-auto p-4">
          {#if isLoading}
            <div class="flex justify-center items-center py-20 text-slate-400">
              {$_("common.loading") || "読み込み中..."}
            </div>
          {:else if filteredTemplates.length === 0}
            <div class="text-center py-16 text-slate-400">
              {$_("AddPolling.NoMatches")}
            </div>
          {:else}
            <div class="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-white dark:bg-slate-950/40">
              <table class="w-full text-left border-collapse text-xs">
                <thead
                  class="bg-slate-100/70 dark:bg-slate-800/60 text-slate-600 dark:text-slate-400 font-semibold border-b border-slate-200 dark:border-slate-800 select-none"
                >
                  <tr>
                    <th
                      class="px-3 py-2.5 w-16 cursor-pointer hover:bg-slate-200/50"
                      onclick={() => handleSort("ID")}
                    >
                      <div class="flex items-center gap-1">
                        ID
                        <ArrowUpDown class="h-3 w-3 opacity-60" />
                      </div>
                    </th>
                    <th
                      class="px-3 py-2.5 w-72 cursor-pointer hover:bg-slate-200/50"
                      onclick={() => handleSort("Name")}
                    >
                      <div class="flex items-center gap-1">
                        {$_("polling.name")}
                        <ArrowUpDown class="h-3 w-3 opacity-60" />
                      </div>
                    </th>
                    <th
                      class="px-3 py-2.5 w-28 cursor-pointer hover:bg-slate-200/50"
                      onclick={() => handleSort("Type")}
                    >
                      <div class="flex items-center gap-1">
                        {$_("polling.type")}
                        <ArrowUpDown class="h-3 w-3 opacity-60" />
                      </div>
                    </th>
                    <th
                      class="px-3 py-2.5 w-36 cursor-pointer hover:bg-slate-200/50"
                      onclick={() => handleSort("Mode")}
                    >
                      <div class="flex items-center gap-1">
                        {$_("polling.mode")}
                        <ArrowUpDown class="h-3 w-3 opacity-60" />
                      </div>
                    </th>
                    <th class="px-3 py-2.5">{$_("list.col.descr")}</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-slate-100 dark:divide-slate-800/60">
                  {#each paginatedTemplates as t}
                    <tr
                      class="cursor-pointer transition-all border-l-4 {selectedId === t.ID
                        ? 'border-l-blue-600 dark:border-l-blue-400 bg-blue-100/90 dark:bg-blue-600/30 text-blue-950 dark:text-blue-50 font-medium shadow-sm'
                        : 'border-l-transparent hover:bg-slate-50 dark:hover:bg-slate-900/60'}"
                      onclick={() => (selectedId = t.ID)}
                      ondblclick={handleApply}
                    >
                      <td class="px-3 py-2.5 font-mono">
                        {#if selectedId === t.ID}
                          <div class="flex items-center gap-1 font-bold text-blue-600 dark:text-blue-400">
                            <CheckCircle2 class="h-3.5 w-3.5 fill-blue-600 text-white dark:fill-blue-400 dark:text-slate-950 shrink-0" />
                            <span>{t.ID}</span>
                          </div>
                        {:else}
                          <span class="text-slate-400 dark:text-slate-500">{t.ID}</span>
                        {/if}
                      </td>
                      <td class="px-3 py-2.5 font-semibold">
                        <div class="flex items-center gap-1.5">
                          <span class={selectedId === t.ID ? "text-blue-900 dark:text-blue-200 font-bold" : "text-slate-900 dark:text-slate-100"}>
                            {t.Name}
                          </span>
                          {#if t.AutoParam}
                            <span
                              class="rounded px-1.5 py-0.2 text-[9px] bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/30 whitespace-nowrap"
                            >
                              自動展開
                            </span>
                          {/if}
                        </div>
                      </td>
                      <td class="px-3 py-2.5 whitespace-nowrap">
                        <span
                          class="inline-block rounded px-2 py-0.5 text-[10px] font-bold uppercase transition-colors {selectedId === t.ID
                            ? 'bg-blue-600 dark:bg-blue-500 text-white border border-blue-600 dark:border-blue-400 shadow-sm'
                            : 'bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300'}"
                        >
                          {renderPollingType(t.Type)}
                        </span>
                      </td>
                      <td class="px-3 py-2.5 font-mono {selectedId === t.ID ? 'text-blue-900 dark:text-blue-200 font-semibold' : 'text-slate-500 dark:text-slate-400'}">
                        {t.Mode || "-"}
                      </td>
                      <td class="px-3 py-2.5 {selectedId === t.ID ? 'text-blue-950 dark:text-blue-100 font-medium' : 'text-slate-600 dark:text-slate-300'}">
                        {t.Descr}
                      </td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          {/if}
        </div>

        <!-- Table Pagination Bar -->
        <div
          class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/60 px-5 py-2 text-xs text-slate-600 dark:text-slate-400 shrink-0"
        >
          <div class="flex items-center gap-3">
            <span>表示件数:</span>
            <select
              bind:value={pageSize}
              onchange={() => (currentPage = 1)}
              class="rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 px-2 py-1 text-xs text-slate-700 dark:text-slate-200 focus:outline-none cursor-pointer"
            >
              <option value={10}>10</option>
              <option value={20}>20</option>
              <option value={50}>50</option>
              <option value={100}>100</option>
              <option value={-1}>全件</option>
            </select>

            <span class="font-mono text-[11px] text-slate-500 dark:text-slate-400">
              {#if totalCount > 0}
                {rangeFrom} - {rangeTo} / {totalCount} 件
              {:else}
                0 件
              {/if}
            </span>
          </div>

          {#if pageSize !== -1 && totalPages > 1}
            <div class="flex items-center gap-1">
              <button
                type="button"
                disabled={validCurrentPage <= 1}
                onclick={() => (currentPage = 1)}
                class="rounded-lg p-1.5 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white disabled:opacity-30 disabled:hover:bg-transparent cursor-pointer transition-colors"
                title={$_("report.firstPage") || "最初のページ"}
              >
                <ChevronsLeft class="h-4 w-4" />
              </button>

              <button
                type="button"
                disabled={validCurrentPage <= 1}
                onclick={() => (currentPage = validCurrentPage - 1)}
                class="rounded-lg p-1.5 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white disabled:opacity-30 disabled:hover:bg-transparent cursor-pointer transition-colors"
                title={$_("report.prevPage") || "前のページ"}
              >
                <ChevronLeft class="h-4 w-4" />
              </button>

              <span class="px-2 font-mono text-xs text-slate-700 dark:text-slate-300 font-semibold">
                {validCurrentPage} / {totalPages}
              </span>

              <button
                type="button"
                disabled={validCurrentPage >= totalPages}
                onclick={() => (currentPage = validCurrentPage + 1)}
                class="rounded-lg p-1.5 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white disabled:opacity-30 disabled:hover:bg-transparent cursor-pointer transition-colors"
                title={$_("report.nextPage") || "次のページ"}
              >
                <ChevronRight class="h-4 w-4" />
              </button>

              <button
                type="button"
                disabled={validCurrentPage >= totalPages}
                onclick={() => (currentPage = totalPages)}
                class="rounded-lg p-1.5 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white disabled:opacity-30 disabled:hover:bg-transparent cursor-pointer transition-colors"
                title={$_("report.lastPage") || "最後のページ"}
              >
                <ChevronsRight class="h-4 w-4" />
              </button>
            </div>
          {/if}
        </div>

        <!-- Footer Actions -->
        <div
          class="flex items-center justify-between border-t border-slate-200 dark:border-slate-800 px-5 py-3 bg-slate-50 dark:bg-slate-950/80 text-xs"
        >
          <!-- Left: Import from file & Blank -->
          <div class="flex items-center gap-2">
            <label
              class="cursor-pointer rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 px-3 py-1.5 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 flex items-center gap-1.5 transition-colors"
            >
              <Upload class="h-3.5 w-3.5" />
              <span>{$_("AddPolling.ImportFromFile")}</span>
              <input
                type="file"
                accept=".json"
                class="hidden"
                onchange={handleImportFile}
              />
            </label>

            <button
              type="button"
              onclick={handleCreateBlank}
              class="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 px-3 py-1.5 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <Plus class="h-3.5 w-3.5" />
              <span>{$_("AddPolling.CreateBlank")}</span>
            </button>
          </div>

          <!-- Right: Cancel & Apply -->
          <div class="flex items-center gap-2">
            <button
              type="button"
              onclick={() => (show = false)}
              class="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 px-4 py-1.5 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 cursor-pointer"
            >
              {$_("common.cancel")}
            </button>

            <button
              type="button"
              disabled={!selectedTemplate || isAutoGenerating}
              onclick={handleApply}
              class="rounded-xl bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-semibold px-4 py-1.5 flex items-center gap-1.5 shadow-sm transition-all cursor-pointer"
            >
              <CheckCircle2 class="h-4 w-4" />
              <span>
                {selectedTemplate?.AutoParam
                  ? $_("AddPolling.AutoDeploy")
                  : $_("AddPolling.ApplyTemplate")}
              </span>
            </button>
          </div>
        </div>
      {/if}
    </div>
  </div>
{/if}
